services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: creative-share-app-dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: development
      PORT: 3000
      HOSTNAME: 0.0.0.0
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

  db:
    env_file:
      - .env
    image: postgres:18
    container_name: creative-share-db-dev
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data_dev:
